# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0085_auto_20190116_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfund',
            name='annual_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenfund',
            name='revolving_fund',
            field=models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], help_text=b'Indicate "Yes" if this is a revolving loan fund (i.e.,\n        the fund makes loans that are eventually repaid back into the fund).', verbose_name=b'Revolving Loan Fund'),
        ),
        migrations.AlterField(
            model_name='greenfund',
            name='student_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
