# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0086_auto_20190116_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfund',
            name='revolving_fund',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], help_text=b'Indicate "Yes" if this is a revolving loan fund (i.e.,\n        the fund makes loans that are eventually repaid back into the fund).', max_length=3, verbose_name=b'Revolving Loan Fund'),
        ),
    ]
