# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_greenpowerfinanceoption_greenpowerinstallation_greenpowerlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Primary Funding Source',
                'verbose_name_plural': 'Primary Funding Sources',
            },
        ),
    ]
