from .types.academic import AcademicProgramIndex
from .types.casestudies import CaseStudyIndex
from .types.centers import CenterAndInstituteIndex
from .types.courses import MaterialIndex
from .types.outreach import OutreachMaterialIndex
from .types.photographs import PhotographIndex
from .types.presentations import PresentationIndex
from .types.publications import PublicationIndex
from .types.tools import ToolIndex
from .types.videos import VideoIndex
