---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - hub/static/vendor/**/*
  - hub/imports/**/*
  - hub/exports/**/*
  - "**/migrations/*"
