language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
  - SECRET_KEY=blahblahblah
  - AASHE_DRUPAL_URI=http://www.aashe.org/services/xmlrpc
  - AASHE_DRUPAL_KEY_DOMAIN=acupcc.aashe.org
  - AASHE_DRUPAL_COOKIE_DOMAIN=.aashe.org
  - secure: sA/AAobEg7ROqJZBZbl9BEf8btE+WsEwtpfWpcENMEggi7MafaStLZcrP0dA25QV1J9PvWTX9gQMIrC5Yd+bsA0GX39C3KH2OmzqDZW1+oNUtt2nTLmiQZAQpnci5fNv8PXePodsdEF/45am7+sK9FCB5sHH9tIs9x6VqZiHAGnMTh0PreCns9AiO6JCY0+0/Ch/iTdK/LGdJsqjdwO7mEIm9tqNAVojzfAVQu0zlwXCVWfQpRBBLgAczEUbDhZM7y8+OZ7X7jwY1O+SsOTuw5UHOGKJ1iD4zFluT0WL+TWZB4e39gmxilpd2aj68wwwKsaIPIV/6DIltFLtOCP4AplBT2LhKL5ews19ZBDk8Mi6HvQHYqxZfCqDDZFj5jgSzCB6iiLBxYjw5/DdsZuJz6D67/q632oIK8Tq0udm9FWWTZ8/1+m/e2si7kNGvsEiwUydog1N6DvYLxxDB7Y/5pU9GrHST9JFVBKIyhR3RZchOgUjFl1BNK9CSOE8rBeN2AOZ6Gs1P/gbFPQTljWRzQvL4hAVG+fJeq7jAeqIurZpikURbd4az9QSmmqLexuWGu/NW0HEQqZtA6KDlZrEZ/fVbxSsbt5xzqWRIIHIrzegzvn9RwWqRGy3VjAccHLF/ghybizLCzFQ3STig3xDK6TmxEuVji77sfmN+j9IF1c=
  - secure: htIbKzn5C6KuRjtSnA7iRPkmXON6LmPTIdHc0G0H5Kv6GMMDghYRZqexZvzUcZiCv6zj0+ml4ibjl2zA8BjymvKkIMoCbQuy6dDAC4BuU/7nuqO8/AQJWlDXfVpIOsNei1bdRRF0RcKHzOHVEf8kr9xHSF5vP5TW+qaqjBDCs5f58zwbA6ayzUYtBZxyxROZWatbGX1gRmcHBkw9jUrkNdUX57bijRJIWwxfuWBFaeLaDKAT0n9KNUQQh8g+mrR1IpV+hVhs1d2kjgoqx+dmW0wlR8+cu5GXWBK3TSqsvaTCD/B5wrkL1c/nSaQ3eF2kxp40lEoHur0dO11oo8TTQSGk8R0MTE6JXFKKN0kCAxS0uMlT7VGNNqElY1Wr7SQ3iq/zejv3iu9VWgdTcr/j0JNAelJ26bUFLEj6zK4Wtv8Gikf3UHoPWUD1UOPvKLTg/0DVj81kqQJ2UkCkH58pPQ5i1Oapj98su5pX4UkI2gh3UPIkoROs5FBGr5UILlyFPbk09k0u+Ccai0uX9ZWmvx/Szx6leNie2HN7TIpi4gsMFnDjhyZsxLHvZl2tVPpxYfbhg64RXAlvSoyxEVp/pqFo4o0MnfggMlh5kckhSYXkOLKj+QeUd8z1omORyVloRf7rqXUisI/Ql/Q98R56fbdcYZ8Tjo++f+DVW4Jplq8=
  - secure: E5NHFsELfdA+S8qsxD9H1utofv3Fhej6p0nqaKIOhaTP50jFwdEx8bqMTgEiF2uCwaGpRdBAqewZ6I9/YS1VS9yNlUpCWzqGyTrcN5xeQdk/lQfGnE2SkXomj10RA1SaTa5euqBZ1dcdb3sTXULhELGuoJvkQUu+sN5LWG59DGljSpZ0fuhGLFJMaeTMdsOT8DrO9WHt4dhY7/Kbeet4kk9hPwidB3mi13nMWANByldkuMk23sgyjzcSuOJE6XS1155mvL97gE1v5JobbA2o2rHEAfBfmUOMrWqtHf437rAGGENBYO58ggXNKu2v2uGq68oqXGGKAvf5NakT8t1HApE0lo+zCZLqjIjlBLeTBxpSSzIPK8+GaKiQZHLd+zwcrBUQ9ylAGSUxZjsWaOhOQbFxQrAmZEkWhRyxXoODqSIIYPNkoijKz3033QeMDQ82qPegYao6QNN9kgUyV5xV6IkujMu9pENiB5q089MfHWWnfiXq3ytb7/bLNi55dLcMRXGQRnH32HauF25e0/1PgMZeLt1hiNcBPkuxntWcUltPh/G49GJ9ZFw9F7rVotYOfjZGLaf0PSXl1QeBpqarZzIlTE9J+JHwPvYiC8yu2LWWAoq6rRUb1h0BlcoHBDA1P4R1z1v52y0WiO9Ad6lnG3V1iG/qUCGichGBXNS/Ja8=
  - secure: ylVwaRm3n803js5uQ+j7Ww42V/pBKVy1538twdisUMb7tOehzBu6H8Oy2z+p+jLknirc5PtQrN9OxD1UYYtG4hsyJ+Fxfx6Lii31ADQOktgYxeVEHrCLiBce5X5hZRMx1QpfMwoVEvqjtvPW2KgcxI/58bF+RrZcrBguw6Vn2JcY1AeiJR+Ql7uXWqSd46xbDFuGZihrZfenwlF7ait/ZP0/FTk+OK7Z7lk9eQehci6TJTm0Lip60mK7vOPvBJwlYP9rs50WUbtPa7YYQZ2cNwbX7ge2tlOn/Sz9Wnaz5KEbse1l9wk2tED+4jJi5IheUxsxII43pfOWfiknKNKl1m7BL2uxyXquL8p2nYWDbF9zimUWtcQMMZgWR1v7Okpdyw1Hr76DVXon1ancSyZStbIO0v2G+j6ZwHAWY5jmlQJDocH2pe2qjJevl3Wlg+pmmhmiQ3i3REsTK51b5zlK0at+WZbw+Y+8y6UiJ3lIM3qXlaBDAE0/NotkE8s3r674NB/H4S5CJZ2zkzCVe0sqjF9BxrYok5LmEzJlhmn8VvrUYkAyvWhLMTd//VM/jp+S/PniLwEwo1JFs21UR7flx5aE38q419++TU1qxhFPbnhVhkpr1RddTLWzb3gxSZjwwzQRxABGL57ItSYzlW5qtHUIJGLlKIJI1tKI5Mxp3lo=
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py collectstatic
script: coverage run manage.py test
after_success: coveralls
notifications:
  email: false
