# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0079_auto_20160801_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='med_thumbnail',
            field=models.URLField(default='/static/images/300x300_blank.png'),
        ),
        migrations.AddField(
            model_name='image',
            name='small_thumbnail',
            field=models.URLField(default='/static/images/100x100_blank.png'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='timeline',
            field=models.TextField(help_text=b'Describe how long this project took from start to finish\n        and provide a list of key project milestones in chronological\n        order.', verbose_name=b'Project Timeline'),
        ),
        migrations.AlterField(
            model_name='centerandinstitute',
            name='budget',
            field=models.PositiveIntegerField(blank=True, help_text=b'in U.S. dollars', null=True, verbose_name=b'Total operating budget for the center or institute\n        (excluding salaries)?'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='date_created',
            field=models.DateField(blank=True, help_text="Enter the date when this resource was created, founded,\n        published, or presented. If you don't know the exact date, choose the\n        first day of the month. Use January 1 if you only know the year. You\n        can use the calendar widget or type in a date in YYYY-MM-DD format.", null=True, verbose_name='Date Created, Published or Presented'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Styling with\n        <a href="https://simplemde.com/markdown-guide" target="_blank">\n        Markdown</a>\n        is supported', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='course_level',
            field=models.CharField(blank=True, choices=[(b'introductory', b'Introductory'), (b'intermediate', b'Intermediate'), (b'advanced', b'Advanced')], help_text=b'100-level courses (or equivalents) may be designated as\n        introductory, 200- or 300-level as intermediate, and 400-level or\n        graduate courses as advanced.', max_length=50, null=True, verbose_name=b'Course Level'),
        ),
    ]
