# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:36
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20160924_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Generic Content Type', 'verbose_name_plural': '- All Content Types -'},
        ),
        migrations.AddField(
            model_name='contenttype',
            name='authors_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='files_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='images_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
