# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20160924_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPowerProject',
            fields=[
                ('contenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentType')),
                ('project_size', models.PositiveIntegerField()),
                ('annual_production', models.PositiveIntegerField(blank=True, null=True)),
                ('installed_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('first_installation_type', models.CharField(choices=[(b'solar-canopy', b'Solar - Canopy'), (b'solar-rooftop', b'Solar - Roof Top Mount'), (b'solar-wall', b'Solar - Wall Mount'), (b'solar-ground-pole', b'Solar - Ground or Pole Mount'), (b'solar-building-photovoltaic', b'Solar - Building Integrated Photovoltaic'), (b'solar-other', b'Solar - Other')], max_length=200)),
                ('second_installation_type', models.CharField(choices=[(b'solar-canopy', b'Solar - Canopy'), (b'solar-rooftop', b'Solar - Roof Top Mount'), (b'solar-wall', b'Solar - Wall Mount'), (b'solar-ground-pole', b'Solar - Ground or Pole Mount'), (b'solar-building-photovoltaic', b'Solar - Building Integrated Photovoltaic'), (b'solar-other', b'Solar - Other')], max_length=200)),
                ('third_installation_type', models.CharField(choices=[(b'solar-canopy', b'Solar - Canopy'), (b'solar-rooftop', b'Solar - Roof Top Mount'), (b'solar-wall', b'Solar - Wall Mount'), (b'solar-ground-pole', b'Solar - Ground or Pole Mount'), (b'solar-building-photovoltaic', b'Solar - Building Integrated Photovoltaic'), (b'solar-other', b'Solar - Other')], max_length=200)),
                ('ownership_type', models.CharField(choices=[(b'unknown', b'Unknown'), (b'institution-owned', b'Institution Owned'), (b'third-party-lease', b'Third-party Owned (Lease)'), (b'third-party-purchase', b'Third-party Owned (Power Purchase Agreement')], max_length=200)),
            ],
            options={
                'verbose_name': 'Green Power Project',
                'verbose_name_plural': 'Green Power Projects',
            },
            bases=('content.contenttype',),
        ),
    ]
