# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 19:52
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_auto_20161030_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
