# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_greenpowerfinancing_greenpowerinstallation_greenpowerlocation'),
        ('content', '0081_auto_20170720_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPowerProject',
            fields=[
                ('contenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentType')),
                ('project_size', models.PositiveIntegerField()),
                ('annual_production', models.PositiveIntegerField(blank=True, null=True)),
                ('installed_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('ownership_type', models.CharField(choices=[(b'unknown', b'Unknown'), (b'institution-owned', b'Institution Owned'), (b'third-party-lease', b'Third-party owned (lease)'), (b'third-party-purchase', b'Third-party owned (power purchase agreement)')], max_length=200)),
                ('money_saver', models.CharField(choices=[(b'yes', b'Yes'), (b'no', b'No'), (b'unknown', b'Unknown')], max_length=100)),
                ('cost_savings_desc', models.TextField(blank=True, null=True)),
                ('starting_ppa_price', models.CharField(blank=True, choices=[(b'< 3', b'< 3'), (b'4 - 4.9', b'4 - 4.9'), (b'5 - 5.9', b'5 - 5.9'), (b'6 - 6.9', b'6 - 6.9'), (b'7 - 7.9', b'7 - 7.9'), (b'8 - 8.9', b'8 - 8.9'), (b'9 - 9.9', b'9 - 9.9'), (b'10 - 10.9', b'10 - 10.9'), (b'11 - 11.9', b'11 - 11.9'), (b'> 12', b'> 12')], max_length=50, null=True)),
                ('ppa_escalator', models.CharField(blank=True, choices=[(b'< 3', b'< 3'), (b'4 - 4.9', b'4 - 4.9'), (b'5 - 5.9', b'5 - 5.9'), (b'6 - 6.9', b'6 - 6.9'), (b'7 - 7.9', b'7 - 7.9'), (b'8 - 8.9', b'8 - 8.9'), (b'9 - 9.9', b'9 - 9.9'), (b'10 - 10.9', b'10 - 10.9'), (b'11 - 11.9', b'11 - 11.9'), (b'> 12', b'> 12')], max_length=50, null=True)),
                ('ppa_escalator_desc', models.TextField(blank=True, null=True)),
                ('ppa_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('finance_sources', models.ManyToManyField(help_text=b'Select up to 3', to='metadata.GreenPowerFinancing', verbose_name=b'Green Power Finanance Source')),
                ('installations', models.ManyToManyField(help_text=b'Select up to three', to='metadata.GreenPowerInstallation', verbose_name=b'Green Power Installation')),
                ('locations', models.ManyToManyField(help_text=b'Select up to 2', to='metadata.GreenPowerLocation', verbose_name=b'Green Power Location')),
            ],
            options={
                'verbose_name': 'Green Power Project',
                'verbose_name_plural': 'Green Power Projects',
            },
            bases=('content.contenttype',),
        ),
    ]
