# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models

def cast_text_to_float(apps, schema_editor):
    GreenPowerProject = apps.get_model("content", "GreenPowerProject")

    for gpp in GreenPowerProject.objects.all():
        gpp.casted_project_size = float(gpp.project_size.replace(',', ''))
        gpp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_greenpowerproject'),
    ]

    operations = [
        # Add new field to store casted float
        migrations.AddField(
            model_name='GreenPowerProject',
            name='casted_project_size',
            field=models.FloatField(null=True, blank=True, default=None),
        ),

        # migrate data to populate the field
        migrations.RunPython(cast_text_to_float),

        # delete the original field
        migrations.RemoveField(
            model_name='GreenPowerProject',
            name='project_size',
        ),

        # change name of new field to old field name
        migrations.RenameField(
            model_name='GreenPowerProject',
            old_name='casted_project_size',
            new_name='project_size',
        ),
    ]
