# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_auto_20161101_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='authors_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
