# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_auto_20161101_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='authors_search_vector',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='files_search_vector',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='images_search_vector',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='websites_search_vector',
        ),
        migrations.AddField(
            model_name='contenttype',
            name='files_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='images_search_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
