# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_fundingsource'),
        ('content', '0084_auto_20190103_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfund',
            name='annual_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenfund',
            name='funding_sources',
            field=models.ManyToManyField(help_text=b'Select up to three funding sources.', to='metadata.FundingSource', verbose_name=b'Primary Funding Source(s)'),
        ),
        migrations.AddField(
            model_name='greenfund',
            name='revolving_fund',
            field=models.BooleanField(default=False, help_text=b'Indicate "Yes" if this is a revolving loan fund (i.e.,\n        the fund makes loans that are eventually repaid back into the fund).', verbose_name=b'Revolving Loan Fund'),
        ),
        migrations.AddField(
            model_name='greenfund',
            name='student_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
