# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-25 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0088_auto_20190725_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_Tagulous_ContentType_keywords',
            new_name='Tagulous_ContentType_keywords',
        ),
    ]
