# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_new_rss_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPowerFinancing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('operating-budget', 'Operating budget'), ('endowment', 'Endowment'), ('capital-budget', 'Capital budget'), ('third-party', 'Third party'), ('donation', 'Donation')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GreenPowerInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('solar-canopy', 'Solar - Canopy'), ('solar-rooftop', 'Solar - Roof Top Mount'), ('solar-wall', 'Solar - Wall Mount'), ('solar-ground-pole', 'Solar - Ground or Pole Mount'), ('solar-building-photovoltaic', 'Solar - Building Integrated Photovoltaic'), ('solar-other', 'Solar - Other'), ('wind-horizontal', 'Wind - Horizontal Axis'), ('wind-horizontal', 'Wind - Vertical Axis'), ('hydroelectric', 'Low - Impact Hydroelectric')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GreenPowerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('institution-owned-main', 'Institution-owned property (main campus)'), ('institution-owned-remote', 'Institution-owned property (remote)'), ('Third party-owned', 'Third party-owned property'), ('unknown', 'Unknown')], max_length=100)),
            ],
        ),
    ]
