# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_new_rss_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPowerFinanceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Green Power Finance Option',
                'verbose_name_plural': 'Green Power Finance Options',
            },
        ),
        migrations.CreateModel(
            name='GreenPowerInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Green Power Installation',
                'verbose_name_plural': 'Green Power Installations',
            },
        ),
        migrations.CreateModel(
            name='GreenPowerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Green Power Location',
                'verbose_name_plural': 'Green Power Locations',
            },
        ),
    ]
